### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by RomanVolkov** [argentlabs/application#1]
What exactly I have to use to get application ID?

**Comment by juniset** [comment]
The point of the exercise is for you to figure it out ;-)

**Comment by raphaelbgr** [comment]
The Keccak-256 HASH of my email is d96c28739c0f9601942a2b3c720ec029c9a37e93f74b20ab4173aab6b588cf82, I'm trying to POST to https://api-ropsten.etherscan.io/api

This is what I got so far, I got no idea on how to generate an Appication ID for applying for the Jr Android Job.

![image](https://user-images.githubusercontent.com/6786682/41467493-205ca826-707d-11e8-9a86-5f94f5e481ee.png)
