### ISSUE TITLE
Did I get the BlockchainID right? :)

### ISSUE THREAD

**Issue by claudio-viola** [argentlabs/application#4]
just curious..

**Comment by juniset** [comment]
Yes ;-)

**Comment by herbig** [comment]
Hey Julien, I sent it in a week ago and haven't heard back. Are you still looking?

**Comment by claudio-viola** [comment]
-> https://ropsten.etherscan.io/tx/0xec5749446c42511d0a9d1f30ec4cdbbbc90d1e142d83607880b9dd792f65875d

**Comment by herbig** [comment]
@claudio-viola did you get any response from @juniset?
